# Generated by Django 5.2 on 2025-05-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_recipe_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='instructions',
        ),
    ]
