# Generated by Django 5.2 on 2025-05-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_description_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Supper', 'Supper'), ('UNSTOPPABLE MIDNIGHT SWEETS CRAVE', 'UNSTOPPABLE MIDNIGHT SWEETS CRAVE')], max_length=40),
        ),
    ]
